services:
  - type: web
    name: ai-chess
    env: static
    buildCommand: chmod +x build.sh && ./build.sh
    staticPublishPath: ./build
    envVars:
      - key: NODE_VERSION
        value: 18.17.1
      - key: CI
        value: false
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache 